services:
  web:
    build: .
    image: mon-portfolio
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules



# Et ensuite juste lancer : docker compose up ou docker compose up --build